# Generated by Django 6.0 on 2025-12-06 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.items'),
        ),
        migrations.AddField(
            model_name='carts',
            name='quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.quantity'),
        ),
        migrations.AddField(
            model_name='carts',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='items',
            name='quantity_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.quantity'),
        ),
    ]
