# Generated by Django 6.0 on 2025-12-06 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_carts_items_carts_quantity_carts_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='quantity',
        ),
    ]
