# Generated by Django 6.0 on 2025-12-06 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_items_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carts',
            name='items',
        ),
        migrations.RemoveField(
            model_name='carts',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='items',
            name='quantity_items',
        ),
        migrations.AddField(
            model_name='quantity',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.carts'),
        ),
        migrations.AddField(
            model_name='quantity',
            name='quantity_items',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.items'),
        ),
    ]
