# Generated by Django 6.0 on 2025-12-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_carts_items_remove_carts_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carts',
            name='items',
            field=models.ManyToManyField(blank=True, to='core.items'),
        ),
    ]
