# Generated by Django 6.0 on 2025-12-06 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_carts_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='core.items'),
        ),
    ]
