# Generated by Django 6.0 on 2025-12-07 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_quantity_quantity_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
