# Generated by Django 6.0 on 2025-12-07 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_quantity_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
    ]
