# Generated by Django 6.0 on 2025-12-07 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_quantity_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='price',
            new_name='price_quantity',
        ),
    ]
