# Generated by Django 6.0 on 2025-12-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_price_quantity_price_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='price_quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
        ),
    ]
