# Generated by Django 6.0 on 2025-12-07 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_quantity_price_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='price_quantity',
            new_name='price_in_cart',
        ),
    ]
