# Generated by Django 6.0 on 2025-12-07 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_price_quantity_quantity_price_in_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quantity',
            old_name='price_in_cart',
            new_name='actual_price',
        ),
        migrations.AddField(
            model_name='quantity',
            name='price_for_user',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
        ),
    ]
