# Generated by Django 6.0 on 2025-12-08 08:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_price_in_cart_quantity_actual_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
