# Generated by Django 6.0 on 2025-12-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_carts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.carts'),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='quantity_items',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.items'),
        ),
    ]
