# Generated by Django 6.0 on 2025-12-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_quantity_cart_alter_quantity_quantity_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(),
        ),
    ]
