# Generated by Django 6.0 on 2025-12-09 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_customuser_image_alter_items_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='image',
            new_name='profile_image',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='image',
            new_name='item_image',
        ),
    ]
