# Generated by Django 6.0 on 2025-12-13 05:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_customuser_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('address', models.TextField()),
                ('city', models.CharField()),
                ('postal_code', models.PositiveIntegerField()),
                ('payment_method', models.BooleanField(choices=[('cash_on_delevry', 'cash_on_delevery'), ('easypaisa', 'easypaisa'), ('jazcash', 'jazcash'), ('back_transfer', 'back transfer')])),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
