# Generated by Django 6.0 on 2026-06-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_order_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='OrderTable',
        ),
    ]
