# Generated by Django 6.0 on 2026-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_rename_order_ordertable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delevry', 'cash_on_delevery'), ('easypaisa', 'easypaisa'), ('jazcash', 'jazcash'), ('back_transfer', 'back transfer')]),
        ),
    ]
