# Generated by Django 6.0 on 2026-06-09 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_ordertable_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='order_placed_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordertable',
            name='payment_received',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='price',
            field=models.CharField(default=None),
        ),
        migrations.AddField(
            model_name='ordertable',
            name='quantity',
            field=models.IntegerField(default=None),
        ),
    ]
