# Generated by Django 6.0 on 2026-06-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_ordertable_order_placed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='order_placed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
