# Generated by Django 6.0 on 2026-06-09 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_ordertable_order_placed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField()),
                ('address', models.CharField()),
                ('city', models.CharField()),
                ('postal_code', models.PositiveIntegerField()),
                ('item', models.CharField(default=None)),
                ('order_placed_at', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=None)),
                ('price', models.CharField(default=None)),
                ('payment_received', models.BooleanField(default=0)),
                ('payment_method', models.CharField(choices=[('cash_on_delevry', 'cash_on_delevery'), ('easypaisa', 'easypaisa'), ('jazcash', 'jazcash'), ('back_transfer', 'back transfer')])),
                ('order_on_way', models.BooleanField(default=0)),
                ('order_delivered', models.BooleanField(default=0)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderTable',
        ),
    ]
