# Generated by Django 6.0 on 2026-06-09 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_orders_delete_ordertable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
