# Generated by Django 6.0 on 2026-06-10 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_remove_order_user_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_delivered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_on_way',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=None),
        ),
    ]
