# Generated by Django 6.0 on 2026-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')]),
        ),
    ]
