# Generated by Django 6.0 on 2026-06-12 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='item_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.items'),
        ),
    ]
