# Generated by Django 6.0 on 2026-06-16 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_order_item_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash_on_delevry', 'cash_on_delevery'), ('easypaisa', 'easypaisa'), ('jazcash', 'jazcash'), ('bank_transfer', 'bank transfer')]),
        ),
    ]
