# Generated by Django 6.0 on 2026-06-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Cash On delivery', 'Cash On delivery'), ('Easypaisa', 'Easypaisa'), ('Jazcash', 'Jazcash'), ('Bank Transfer', 'Bank Transfer')]),
        ),
    ]
